global using System.Collections;
global using System.ComponentModel.DataAnnotations;
global using System.Data;
global using System.Data.Common;
global using Xunit;
global using AwesomeAssertions;
global using Microsoft.Data.SqlClient;
global using NSubstitute;
global using RentADeveloper.ArgumentNullGuards;
global using RentADeveloper.SqlConnectionPlus.Converters;
global using RentADeveloper.SqlConnectionPlus.Extensions;
global using RentADeveloper.SqlConnectionPlus.Materializers;
global using static AwesomeAssertions.FluentActions;
global using static RentADeveloper.SqlConnectionPlus.SqlConnectionExtensions;
